import type { ZunoStateEvent } from "@iadev93/zuno";
import type {
	UniverseRecord,
	ZunoAsyncServerPersistence,
	ZunoCompactionPolicy,
	ZunoCompareAndSetResult,
	ZunoReplayBounds,
	ZunoReplayQuery,
} from "@iadev93/zuno/server";

export type ZunoPostgresQueryResult<Row = Record<string, unknown>> = { rows: Row[]; rowCount?: number | null };
export interface ZunoPostgresQueryable { query<Row = Record<string, unknown>>(text: string, values?: readonly unknown[]): Promise<ZunoPostgresQueryResult<Row>>; }
export interface ZunoPostgresClient extends ZunoPostgresQueryable { release?(): void; }
export interface ZunoPostgresPool extends ZunoPostgresQueryable { connect(): Promise<ZunoPostgresClient>; end?(): Promise<void>; }
export type ZunoPostgresPersistenceOptions = { pool: ZunoPostgresPool; tablePrefix?: string };

type StateRow = { store_key: string; state: unknown; version: string | number };
type EventRow = { event_id: string | number; store_key: string; state: unknown; idempotency_key: string | null; durability: "durable" | "ephemeral" | null; operation: "upsert" | "delete" | null; intent: unknown; version: string | number | null; base_version: string | number | null; origin: string | null; ts: string | number | null };

const safePrefix = (value: string) => { if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(value)) throw new Error("PostgreSQL tablePrefix must be a valid SQL identifier"); return value; };
const partitionOf = (storeKey: string) => storeKey.split(":", 1)[0] ?? "";
const topicOf = (storeKey: string) => storeKey.split(":")[1] ?? "";
const safeInteger = (value: string | number, field: string): number => { const numeric = typeof value === "number" ? value : Number(value); if (!Number.isSafeInteger(numeric)) throw new RangeError(`PostgreSQL ${field} exceeds JavaScript safe-integer range`); return numeric; };
const nullableSafeInteger = (value: string | number | null, field: string) => value == null ? undefined : safeInteger(value, field);
const toEvent = (row: EventRow): ZunoStateEvent => ({ storeKey: row.store_key, state: row.state, idempotencyKey: row.idempotency_key ?? undefined, durability: row.durability ?? undefined, operation: row.operation ?? undefined, intent: row.intent as ZunoStateEvent["intent"], version: nullableSafeInteger(row.version, "event version"), baseVersion: nullableSafeInteger(row.base_version, "event base_version"), origin: row.origin ?? undefined, ts: row.ts == null ? undefined : safeInteger(row.ts, "event timestamp"), eventId: safeInteger(row.event_id, "event_id") });

/** PostgreSQL-backed durable authority. The caller owns the supplied pool. */
export class PostgresZunoServerPersistence implements ZunoAsyncServerPersistence {
	private readonly pool: ZunoPostgresPool; private readonly states: string; private readonly events: string;
	constructor(options: ZunoPostgresPersistenceOptions) { this.pool = options.pool; const prefix = safePrefix(options.tablePrefix ?? "zuno"); this.states = `${prefix}_states`; this.events = `${prefix}_events`; }
	async initialize(): Promise<void> {
		await this.pool.query(`CREATE TABLE IF NOT EXISTS ${this.states} (store_key TEXT PRIMARY KEY, partition_key TEXT NOT NULL, topic TEXT NOT NULL, state JSONB, version BIGINT NOT NULL CHECK (version >= 0))`);
		await this.pool.query(`CREATE TABLE IF NOT EXISTS ${this.events} (event_id BIGSERIAL PRIMARY KEY, store_key TEXT NOT NULL, partition_key TEXT NOT NULL, topic TEXT NOT NULL, state JSONB, idempotency_key TEXT, durability TEXT NOT NULL DEFAULT 'durable', operation TEXT NOT NULL DEFAULT 'upsert', intent JSONB, version BIGINT, base_version BIGINT, origin TEXT, ts BIGINT NOT NULL, UNIQUE (partition_key, idempotency_key))`);
		await this.pool.query(`CREATE INDEX IF NOT EXISTS ${this.events}_store_event_idx ON ${this.events} (store_key, event_id)`); await this.pool.query(`CREATE INDEX IF NOT EXISTS ${this.events}_partition_topic_event_idx ON ${this.events} (partition_key, topic, event_id)`); await this.pool.query(`CREATE INDEX IF NOT EXISTS ${this.events}_operation_ts_idx ON ${this.events} (operation, ts)`);
	}
	async close(): Promise<void> { await this.pool.end?.(); }
	async getRecord(storeKey: string): Promise<UniverseRecord | undefined> { const result = await this.pool.query<StateRow>(`SELECT store_key, state, version FROM ${this.states} WHERE store_key = $1`, [storeKey]); const row = result.rows[0]; return row ? { state: row.state, version: safeInteger(row.version, "state version") } : undefined; }
	async getSnapshot(partition?: string, topics?: ReadonlySet<string>): Promise<Record<string, UniverseRecord>> { const values: unknown[] = []; const where: string[] = []; if (partition) { values.push(partition); where.push(`partition_key = $${values.length}`); } if (topics) { const topicList = [...topics]; if (topicList.length === 0) return {}; values.push(topicList); where.push(`topic = ANY($${values.length}::text[])`); } const result = await this.pool.query<StateRow>(`SELECT store_key, state, version FROM ${this.states}${where.length ? ` WHERE ${where.join(" AND ")}` : ""}`, values); const snapshot: Record<string, UniverseRecord> = {}; for (const row of result.rows) snapshot[row.store_key] = { state: row.state, version: safeInteger(row.version, "state version") }; return snapshot; }
	async readEvents(query: ZunoReplayQuery): Promise<ZunoStateEvent[]> { if (query.limit <= 0 || (query.topics && query.topics.size === 0)) return []; const values: unknown[] = [query.afterEventId]; const where = ["event_id > $1"]; if (query.partition) { values.push(query.partition); where.push(`partition_key = $${values.length}`); } if (query.topics) { values.push([...query.topics]); where.push(`topic = ANY($${values.length}::text[])`); } values.push(query.limit); const result = await this.pool.query<EventRow>(`SELECT * FROM ${this.events} WHERE ${where.join(" AND ")} ORDER BY event_id ASC LIMIT $${values.length}`, values); return result.rows.map(toEvent); }
	async getReplayBounds(): Promise<ZunoReplayBounds> { const result = await this.pool.query<{ first_event_id: string | number | null; last_event_id: string | number | null }>(`SELECT MIN(event_id) AS first_event_id, MAX(event_id) AS last_event_id FROM ${this.events}`); const row = result.rows[0]; return { firstEventId: row?.first_event_id == null ? undefined : safeInteger(row.first_event_id, "first event_id"), lastEventId: row?.last_event_id == null ? 0 : safeInteger(row.last_event_id, "last event_id") }; }
	async appendEvent(event: ZunoStateEvent, maxEvents: number): Promise<ZunoStateEvent> { const client = await this.pool.connect(); try { await client.query("BEGIN"); const authoritative = await this.insertEvent(client, event); await this.trimEvents(client, maxEvents); await client.query("COMMIT"); return authoritative; } catch (error) { await this.rollbackQuietly(client); throw error; } finally { client.release?.(); } }
	async compareAndSet(event: ZunoStateEvent, maxEvents: number): Promise<ZunoCompareAndSetResult> { const client = await this.pool.connect(); try { await client.query("BEGIN"); const partition = partitionOf(event.storeKey); if (event.idempotencyKey) { await this.lock(client, `idempotency:${partition}:${event.idempotencyKey}`); const duplicate = await client.query<EventRow>(`SELECT * FROM ${this.events} WHERE partition_key = $1 AND idempotency_key = $2 LIMIT 1`, [partition, event.idempotencyKey]); if (duplicate.rows[0]) { await client.query("COMMIT"); return { ok: true, event: toEvent(duplicate.rows[0]), duplicate: true }; } } await this.lock(client, `store:${event.storeKey}`); const locked = await client.query<StateRow>(`SELECT store_key, state, version FROM ${this.states} WHERE store_key = $1 FOR UPDATE`, [event.storeKey]); const current: UniverseRecord = locked.rows[0] ? { state: locked.rows[0].state, version: safeInteger(locked.rows[0].version, "state version") } : { state: undefined, version: 0 }; if (typeof event.baseVersion === "number" && event.baseVersion !== current.version) { await client.query("ROLLBACK"); return { ok: false, current }; } if (current.version >= Number.MAX_SAFE_INTEGER) throw new RangeError("PostgreSQL state version exhausted JavaScript safe-integer range"); const version = current.version + 1; if ((event.operation ?? "upsert") === "delete") await client.query(`DELETE FROM ${this.states} WHERE store_key = $1`, [event.storeKey]); else await client.query(`INSERT INTO ${this.states} (store_key, partition_key, topic, state, version) VALUES ($1, $2, $3, $4, $5) ON CONFLICT (store_key) DO UPDATE SET state = EXCLUDED.state, version = EXCLUDED.version`, [event.storeKey, partition, topicOf(event.storeKey), event.state ?? null, version]); const authoritative = await this.insertEvent(client, { ...event, durability: "durable", operation: event.operation ?? "upsert", version }); await this.trimEvents(client, maxEvents); await client.query("COMMIT"); return { ok: true, event: authoritative }; } catch (error) { await this.rollbackQuietly(client); throw error; } finally { client.release?.(); } }
	async compact(policy: ZunoCompactionPolicy, now = Date.now()): Promise<number> { const before = await this.countEvents(); const client = await this.pool.connect(); try { await client.query("BEGIN"); if (policy.retentionMs != null) await client.query(`DELETE FROM ${this.events} WHERE operation <> 'delete' AND ts < $1`, [now - policy.retentionMs]); if (policy.tombstoneRetentionMs != null) await client.query(`DELETE FROM ${this.events} WHERE operation = 'delete' AND ts < $1`, [now - policy.tombstoneRetentionMs]); await this.trimEvents(client, policy.maxEvents); await client.query("COMMIT"); } catch (error) { await this.rollbackQuietly(client); throw error; } finally { client.release?.(); } const after = await this.countEvents(); return Math.max(0, before - after); }
	async clear(): Promise<void> { await this.pool.query(`TRUNCATE TABLE ${this.events}, ${this.states} RESTART IDENTITY`); }
	private async lock(client: ZunoPostgresQueryable, key: string): Promise<void> { await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1, 0))", [key]); }
	private async rollbackQuietly(client: ZunoPostgresQueryable): Promise<void> { try { await client.query("ROLLBACK"); } catch {} }
	private async countEvents(): Promise<number> { const result = await this.pool.query<{ count: string | number }>(`SELECT COUNT(*) AS count FROM ${this.events}`); return safeInteger(result.rows[0]?.count ?? 0, "event count"); }
	private async insertEvent(client: ZunoPostgresQueryable, event: ZunoStateEvent): Promise<ZunoStateEvent> { const result = await client.query<EventRow>(`INSERT INTO ${this.events} (store_key, partition_key, topic, state, idempotency_key, durability, operation, intent, version, base_version, origin, ts) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`, [event.storeKey, partitionOf(event.storeKey), topicOf(event.storeKey), event.state ?? null, event.idempotencyKey ?? null, event.durability ?? "durable", event.operation ?? "upsert", event.intent ?? null, event.version ?? null, event.baseVersion ?? null, event.origin ?? null, event.ts ?? Date.now()]); const row = result.rows[0]; if (!row) throw new Error("PostgreSQL did not return the inserted Zuno event"); return toEvent(row); }
	private async trimEvents(client: ZunoPostgresQueryable, maxEvents: number): Promise<void> { await client.query(`DELETE FROM ${this.events} WHERE event_id NOT IN (SELECT event_id FROM ${this.events} ORDER BY event_id DESC LIMIT $1)`, [Math.max(0, maxEvents)]); }
}
